#!/bin/bash 

# Define command-line arguments

RESOURCE_TYPE=$3
FIRST="${1:-top}" #if no argument take top
SECOND="${2:-pod}"
THIRD="${3:-kube-system}"
# Retrieve resource usage statistics from Kubernetes
kubectl $FIRST $SECOND -n $THIRD | tail -n +2 | while read line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  echo "Resource         Namespace   Name, CPU, Memory"
  echo $SECOND $THIRD $NAME $CPU $MEMORY
done